# BOLETA DE VENTA DE UN AVION
cliente = input ( " INGRESO EL NOMBRE DEL PASAJERO: " )
dni = int ( input ( " INGRESE EL DNI DEL PASAJERO: " ))
hora = input ( " INGRESO LA HORA DE VUELO: " )
destino = input ( " INGRESO EL DESTINO QUE DESEA IR " )
horas_de_vuelo = int ( input ( " INGRESO EL NUMERO DE HORAS DE VUELO: " ))
monto_por_hora = float ( input ( " INGRESE EL MONTO POR HORA: " ))
total = horas_de_vuelo * monto_por_hora

print ( " ############################################### ######## " )
print ( " # ´´ALEX PRESS´´´ # " )
print ( " # " )
print ( " # CLIENTE: " + cliente)
print ( " # DNI: " + str (dni))
print ( " # HORARIO DE SALIDA: " + hora)
print ( " # DESTINO: " + destino)
print ( " # HORAS DE VUELO: " + str (horas_de_vuelo))
print ( " # MONTO POR HORA: " + str (monto_por_hora))
print ( " # TOTAL: " + str (total))
print ( " # " )
print ( " ############################################### ######## " )
